apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
  namespace: linux
    app: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-container
        image: httpd:2.4
        ports:
        - containerPort: 80
